name: node_io
description: Like dart:io but with Node.js.
version: 1.2.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  file: ^6.0.0
  node_interop:
    git:
      url: https://github.com/blaueeiner/node-interop.git
      path: ./node_interop/
      ref: master
  path: ^1.8.0

dev_dependencies:
  js: ^0.6.3
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^1.12.2
  build_node_compilers:
    git:
      url: https://github.com/blaueeiner/node-interop.git
      path: ./build_node_compilers/
      ref: master
  build_test: ^2.0.0
